name: Build 3DS App

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Upload CIA
        uses: actions/upload-artifact@v4
        with:
          name: BigBang3D-CIA
          path: BigBang3D.cia

      - name: Upload 3DSX
        uses: actions/upload-artifact@v4
        with:
          name: BigBang3D-3DSX
          path: BigBang3D.3ds
