TARGET := BigBang3D
BUILD := build
SOURCES := source

APP_TITLE := Big Bang 3D
APP_DESCRIPTION := Neon arcade explosion
APP_AUTHOR := YourName

LIBS := -lctru -lcitro2d -lcitro3d -lm

include $(DEVKITPRO)/libctru/base_rules
